apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: argodemonotify@gmail.com
spec:
  project: default
  source:
    repoURL: https://github.com/patiltejal40/github-actions-frontend.git
    path: ./Manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - Validate=false
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
