apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: tejalpatil20112000@gmail.com
