# Adding Secret
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  email-username: YXJnb2RlbW9ub3RpZnlAZ21haWwuY29t
  email-password: aWRrZ3hpamdrZXBrcnRxZA==
type: Opaque
# --------------------------------------------------------------------------
#   Encode
# --------------------------------------------------------------------------
# powershell "[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('yourword'))"

# powershell "[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('argoy@gmail.com'))"

# powershell "[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('psw'))"

# --------------------------------------------------------------------------
#   Decode
# --------------------------------------------------------------------------
# powershell "[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('encodedword'))"

# powershell "[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('YXJnb2RlbW9ub3RpZnlAZ21haWwuY29t'))"

# --------------------------------------------------------------------------
#   Encode
# --------------------------------------------------------------------------
# echo -n 'argodemonotify@gmail.com' | base64

# YXJnb2RlbW9ub3RpZnlAZ21haWwuY29t

# --------------------------------------------------------------------------
#   Decode
# --------------------------------------------------------------------------
# echo -n 'lkjhdt' | base64 --decode

# argoy@gmail.com

