# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build_Test_Build-and-Push-to_Docker_SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Gradle-Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Branch
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  SonarCloud-Scan:
    needs: Gradle-Build-And-Test
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  Build-And-Push-Docker-Image:
    needs: SonarCloud-Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Branch
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          export TZ=Asia/Kolkata
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${TIMESTAMP}
          LATEST_TAG=${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-latest
          docker build -t ${IMAGE_TAG} -t ${LATEST_TAG} .
          docker push ${IMAGE_TAG}
          docker push ${LATEST_TAG}
