# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Branch
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      # - name: Print current directory
      #   run: pwd

      # - name: List files in current directory
      #   run: ls -la

      - name: Set up JDK 17 # Required for SonarCloud
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   run: |
      #     TIMESTAMP=$(date +%Y%m%d%H%M%S)
      #     IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/github-actions-frontend:${TIMESTAMP}
      #     docker build -t ${IMAGE_TAG} .
      #     docker push ${IMAGE_TAG}
